import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const w=JSON.parse(readFileSync(new URL('../../qimia-beauty/n8n/qimia-beauty-staging.json',import.meta.url)));
const code=w.nodes.find(n=>n.name==='Configuration').parameters.jsCode.split('// Configure one existing')[0];
const h=Function(code+';return {configGuard,productGuard,hierarchyGuard,validateFacts,reviewDraft,prepareApply,verifyReadback,snapshot,fieldsFor};')();
let passed=0;const test=(name,fn)=>{fn();passed++;console.log('PASS: '+name);};
const clone=x=>structuredClone(x);
const config={stagingOrigin:'https://qimialab.qimia.om',mode:'review',productId:123,expectedSku:'TEST-ONLY',expectedName:'Test only',department:'skin-care',productClass:'beauty',trustedSourceHosts:['example.com'],sourceHints:[],reviewedDraft:null};
const product={id:123,name:'Test only',sku:'TEST-ONLY',parent_id:0,type:'simple',status:'publish',permalink:config.stagingOrigin+'/product/test-only/',categories:[{id:30,slug:'face-serums'}],qimia_product_class:'beauty',qimia_beauty_details:{},stock_status:'outofstock',regular_price:'10',meta_data:[{key:'_qimia_supplement_facts',value:'protected'}]};
const ctx={config,product,baseline:h.snapshot(product)};
const source={url:'https://example.com/exact-label',publisher:'Fixture manufacturer',kind:'manufacturer'};
const research={schema_version:1,product_match:{exact:true,product_id:123,sku:'TEST-ONLY',reason:'Fixture exact identity and size verified from this label.',variant_scope:'single_product'},source,facts:{size:'50 ml',directions_en:'Apply as labelled.',directions_ar:'يُستخدم وفق الإرشادات.'},evidence:{size:{url:source.url,quote:'Contains 50 ml.'},directions_en:{url:source.url,quote:'Apply as labelled.'},directions_ar:{url:source.url,quote:'Apply as labelled.',translation_of:'directions_en'}},conflicts:[],missing_fields:[]};
test('exact staging configuration',()=>h.configGuard(config));
for(const [name,patch] of [['production',{stagingOrigin:'https://qimia.om'}],['unset ID',{productId:0}],['missing identity',{expectedSku:'',expectedName:''}],['invalid class',{productClass:'supplement'}]])test('reject '+name,()=>assert.throws(()=>h.configGuard({...config,...patch})));
test('native Beauty product accepted',()=>h.productGuard(product,config,{'skin-care':['face-serums']}));
for(const [name,patch] of [['supplement',{qimia_product_class:'supplement'}],['wrong SKU',{sku:'WRONG'}],['variation',{type:'variation',parent_id:456}],['production permalink',{permalink:'https://qimia.om/product/test/'}]])test('reject '+name,()=>assert.throws(()=>h.productGuard({...product,...patch},config,{'skin-care':['face-serums']})));
test('source-backed language pair',()=>assert.equal(h.validateFacts(research,ctx).directions_ar,research.facts.directions_ar));
for(const [name,mutate] of [['missing Arabic',r=>delete r.facts.directions_ar],['unsupported oral field',r=>r.facts.serving='1'],['unverified match',r=>r.product_match.exact=false],['incomplete evidence',r=>delete r.evidence.size],['conflicting source',r=>r.conflicts=['different label']],['incorrect INCI',r=>{r.facts.inci='Invented';r.evidence.inci={url:source.url,quote:'Aqua, Glycerin'};}],['retailer source',r=>r.source.kind='retailer']])test('reject '+name,()=>{let r=clone(research);mutate(r);assert.throws(()=>h.validateFacts(r,ctx));});
test('variable formula cannot be generalized',()=>assert.throws(()=>h.validateFacts(research,{...ctx,product:{...product,type:'variable'}})));
const draft=h.reviewDraft(research,ctx);
test('research cannot approve itself',()=>assert.equal(draft.review.approved,false));
test('unreviewed writes rejected',()=>assert.throws(()=>h.prepareApply({...ctx,config:{...config,reviewedDraft:draft}})));
draft.review={approved:true,reviewedBy:'Fixture reviewer',confirmedExactProduct:true,confirmedSources:true,confirmedTranslations:true,confirmedVariantScope:true,approvalText:'APPLY BEAUTY METADATA TO STAGING PRODUCT 123'};
const ready=h.prepareApply({...ctx,config:{...config,reviewedDraft:draft}});
test('only Beauty metadata can be written',()=>assert.deepEqual(Object.keys(ready.body),['qimia_product_class','qimia_beauty_details']));
test('stale product rejected',()=>assert.throws(()=>h.prepareApply({...ctx,baseline:{...ctx.baseline,date_modified_gmt:'changed'},config:{...config,reviewedDraft:draft}})));
const saved={...product,qimia_beauty_details:ready.body.qimia_beauty_details};
test('readback matches',()=>assert.equal(h.verifyReadback(saved,ready).outcome,'verified'));
test('readback rejects stock mutation',()=>assert.throws(()=>h.verifyReadback({...saved,stock_status:'instock'},ready)));
test('readback rejects supplement mutation',()=>assert.throws(()=>h.verifyReadback({...saved,meta_data:[]},ready)));
test('same approved values cause no write',()=>assert.equal(h.prepareApply({...ctx,product:saved,config:{...config,reviewedDraft:draft}}).should_write,false));
test('all six departments supported',()=>{for(const d of ['skin-care','makeup','hair-care','body-care','fragrance','beauty-tools'])assert.ok(h.fieldsFor(d).length>12);});
test('export is independent and has no credentials',()=>{assert.equal(w.active,false);assert.ok(!w.id);for(const n of w.nodes)assert.ok(!n.credentials);assert.deepEqual(w.pinData,{});});
test('manual trigger only, no existing workflow calls',()=>assert.ok(!w.nodes.some(n=>/webhook|scheduleTrigger|executeWorkflow$/.test(n.type))));
test('exactly one PUT, no POST or DELETE',()=>{const http=w.nodes.filter(n=>n.type==='n8n-nodes-base.httpRequest');assert.equal(http.filter(n=>n.parameters.method==='PUT').length,1);assert.ok(http.every(n=>['GET','PUT',undefined].includes(n.parameters.method)));for(const n of http){assert.ok(n.parameters.url.includes('qimialab.qimia.om'));assert.equal(n.parameters.options.redirect.redirect.followRedirects,false);}});
test('review branch cannot reach write',()=>assert.equal(w.connections['Create review draft only'],undefined));
test('embedded code compiles',()=>{for(const n of w.nodes.filter(n=>n.type==='n8n-nodes-base.code'))Function(n.parameters.jsCode);});
console.log(JSON.stringify({passed,failed:0}));
